### PR TITLE
Move screenshots into a subdirectory

### PR DESCRIPTION
**Pull request by troyraen**
I like the screenshots and think they add clarity. Just wondering about putting them in a subdirectory so they're not all in the repo root? I think it's easier to manage that way and makes the repo contents more clear.

### CODE REVIEW

**Review by bsipocz — COMMENTED** [review]
nitpicking, but I would name it differently, either `images`, or `static/images` as we may add other image content to the docs at some point.

**Comment by troyraen** [comment]
My original instinct was to use `images` but that seemed unclear because of all the name collisions (is this Docker images, CCD images, science plots/figures, ...?). But maybe because this repo is strictly documentation it's not as confusing as I first thought?

**Comment by bsipocz** [comment]
Ahh, I see where you're coming from. Maybe then `docs_images`? My only point that a flowchart, or logo or similar could end up in the same directory not just screenshots.

I clearly dealt with more docs and HTML repos than docker repos so have a bias and I'm not sure how standard it is, but at many places, I tend to see these types of images to be dumped under `_static/images` or something similar (So for me dumping docker images in a simple `image` directory feels extremely confusing).

**Comment by troyraen** [comment]
Thinking more... maybe `static/images` is the most future-proof?

**Comment by bsipocz** [comment]
Yes I think so. And I've browsed a little bit more: whether to start it with underscore or not I don't see a clear preference (~50/50 split), and at one places I saw it's being called `assets/images`, but that doesn't feel more clear that `static/images`. Anyway, I really am sorry about this bike shed.

**Pull request merged**
